[package]
name = "yolov8_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cv-convert = "0.24.1"
ndarray = "0.15.6"
opencv = "0.85.1"
ort = "1.16.2"
